### ISSUE TITLE
Can you share the model weights please for the 6 image captioning models

### ISSUE THREAD

**Issue by eslambakr** [princetonvisualai/imagecaptioning-bias#1]
Thanks for sharing the code for your amazing work!

It would be highly appreciated if you can upload the  model weights please for the 6 image captioning models.

Thanks in advance!

**Comment by dorazhao99** [comment]
Hi, I will look to see if I can find the model weights; however, in the meantime, I recommend using the model weights from here [[link](https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/MODEL_ZOO.md)] for FC, Att2In, and Transformer; [AoANet](https://drive.google.com/drive/folders/1ab0iPNyxdVm79ml-oozsIlH7H6t6dIVl); [DiscCap](https://drive.google.com/drive/folders/1_-OpcVmiZ8D4OJH76D0J1l8WXZH-HQmR); and [Oscar](https://github.com/microsoft/Oscar/blob/master/MODEL_ZOO.md#Image-Captioning-on-COCO).
