### ISSUE TITLE
Enquiry for the annotations

### ISSUE THREAD

**Issue by Ashbringer0926** [princetonvisualai/imagecaptioning-bias#2]
Hi there,

Can you provide the annotations for COCO 2014 Val?

**Comment by dorazhao99** [comment]
You can request the annotations using the data request form [[link](https://docs.google.com/forms/d/e/1FAIpQLSdjLGJ2AhOKBGou_VqaWpLJUAL3ieJ2WNmEmGnuIZgCvjbx2Q/viewform)].
